import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MeuMonitor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className=" h-full w-full">
      <body className={`${inter.className} "w-full flex h-full flex-col`}>
        {children}
        <footer className="flex w-full items-center justify-center gap-4 bg-[#0d192b] py-2 text-xs text-white">
          <p>Contrato do Usuário</p>
          <p>Politicas de Privacidade</p>
          <p>Politicas de Cookies</p>
        </footer>
        <Toaster />
      </body>
    </html>
  )
}
